- name: installinh the maven to setup the java environment
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: Setting up the application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install the dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: Renaming the file
  ansible.builtin.command: "mv target/shipping-1.0.jar shipping.jar"
  args:
    chdir: /app

- name: Load the schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql-schema

- name: Copying the service aand restart the service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup