- name: Setup the node environment and install the nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Setup the application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install the dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: loading the schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mongo-schema.yaml

- name: Copying the service and restarting the service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup

  