- name: Installing the Node js by setup the node environment
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: set up the application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Installing the dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: loading the schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mongo-schema

- name: Copying the Service file and restarting
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup


