- name: install the nginx server
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: enable and start the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Removing the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory  

- name: Download the Front end content
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: extracting the front end content to html directory
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copying the Roboshop conf file for creating reverse proxy
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf 
  notify:
  - restarting the nginx service
  
# - name: restarting the nginx service
#   ansible.builtin.service:
#     name: nginx
#     state: restarted
