- name: check whether the user exists or not
  ansible.builtin.command: id roboshop
  register: USERID
  ignore_errors: true

- name: Create the User
  ansible.builtin.user:
    name: roboshop
  when: USERID.rc != 0

- name: Check whether the directory exists or not
  ansible.builtin.stat:
    path: /app
  register: Directory

- name: print the directory existance status
  ansible.builtin.debug:
    msg: "output is {{Directory}}"

- name: Create the app directory
  ansible.builtin.file:
    path: /app
    state: directory
  when: Directory.stat.exists == false

- name: "Download the {{component}} artifact"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "extract the {{component}} artifact"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes # it is used for catalogue file is there in remote machine, if we dont give that ansible will check inside the server
