- name: copying the Mogodb repo file to mongo repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing the Mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Loading the schema
  ansible.builtin.command: "mongo --host mongodb.suhaildevops.online < /app/schema/{{component}}.js"